### ISSUE TITLE
CORS error when using from frontend application

### ISSUE THREAD

**Issue by fabasoad** [Dojeto/LeetcodeAPI#1]
**Steps to reproduce**
1. Create a simple web application with `https://leetcodestats.cyclic.app/<YOUR_USERNAME>` call inside.
2. Host it in GitHub pages.
3. Open it in browser

**Expected behavior**
Call should be valid and 200 status code should be returned with response body.

**Actual behavior**
CORS error is returned and the following error is printed in console:

```text
Access to fetch at 'https://leetcodestats.cyclic.app/johndoe' from origin 'https://johndoe.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Recommendation for fix**
Allow CORS requests from `https://*.github.io`.

**Comment by Dojeto** [comment]
I made this API 6 months ago and at that time, I didn't add cors it was working fine as long as cors changed its privacy.
now I have to add cors in my API and allow all the origins, Right now I am busy with other work it would be grateful if you open a pull request I will review it, else give me some I will add :)

**Comment by fabasoad** [comment]
Hi @Dojeto! PR has been created. Please review. Thanks!
